---
title: "first rmarkdown"
author: "Tina"
date: "12/23/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is a document that has some words and code in it.

# This is a section with some old hw

```{r library, message = FALSE}
library(tidyverse)
```

I use `message = FALSE` in the library code chunk to not show the messages that come with loading the library. 

```{r hw1}
#This is a part of a homework that I randomly copied from DS100.

ggplot(data = diamonds, aes(x = x)) +
  geom_histogram(binwidth = 0.5)
ggplot(data = diamonds, aes(x = y)) +
  geom_histogram(binwidth = 1)
```

This is where I explain what the code does and interpret the results.

```{r hw2}
ggplot(data = diamonds, aes(x = z)) +
  geom_histogram(binwidth = 1)
```

And then I do it again for another graph.

# Next section with other hw

This is from week 9.

```{r libraries2, message = FALSE}
library(tidyverse)
library(Lahman)
library(lubridate)
library(mosaicData)
```

```{r hw3}
Teams_long <- Teams %>%
  filter(teamID == "CHN") %>%
  select(yearID, teamID, HR, HRA) %>%
  pivot_longer(cols = c(HR, HRA),
               names_to = "names",
               values_to = "number")
ggplot(Teams_long, aes(x = yearID, y = number, color = names)) +
  geom_line()
```

